### ISSUE TITLE
The Steam OTP not working correctly

### ISSUE THREAD

**Issue by Nebulosa-Cat** [bitwarden/ios#1034]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

Create a password have totp using steam's proprietary otp (Steam://???.....???)
![image](https://github.com/user-attachments/assets/91c12277-d056-42cf-ad1d-894be022ee1b)

It should generate 5 digit OTP code (Uppercase English and numbers)
You shold see this correct in Dsktop or web browser version bitwaden.
![image](https://github.com/user-attachments/assets/f6d42f92-a3da-49d6-b0f8-1820fb20c118)

But on iOS it gen like normal TOTP as 6 digit numbers.
![image](https://github.com/user-attachments/assets/7bb9f72b-d086-4246-8991-3e719de06479)

### Expected Result

It should gen the correct 5 digit steam proprietary otp code.

### Actual Result

It looks just gen the otp start with steam:// as normal otp

### Build Version

v2024.9.2 (1106)

### Environment Details

- Device: iPhone 12 mini 128G
- OS Version: iOS 18.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi, thanks for reporting this,

This should be resolved by https://github.com/bitwarden/sdk/pull/1144, and once the iOS app is updated to consume these changes.
