### ISSUE TITLE
App crashes when trying to edit entry with empty email/user

### ISSUE THREAD

**Issue by t-moe** [bitwarden/ios#1173]
### Steps To Reproduce

1. Create an entry and leave the email empty
2. Open the entry again, press edit

### Expected Result

Showing the edit dialog

### Actual Result

Crash

### Build Version

latest from app store: 2024.11.0 (1680)

### What server are you connecting to?

N/A

### Environment Details

Iphone 7 Plus  
Ios 15.8.3

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello,

Can you please share your OS version?

**Comment by t-moe** [comment]
I tried to reproduce the issue now, and I'm unable to cause a crash now... Not sure what it was. I'll close the issue and reopen if I can reproduce reliably..
