### ISSUE TITLE
Cannot install Beta client on Apple Watch

### ISSUE THREAD

**Issue by navels** [bitwarden/ios#1194]
### Steps To Reproduce

1. Go to Watch app on iPhone
2. Under Available Apps, see Bitwarden
3. Click "Install"

### Expected Result

App installs to Apple Watch

### Actual Result

Install icon spins without installing the app

### Screenshots or Videos

![IMG_5030](https://github.com/user-attachments/assets/e2a78b93-46b8-4ffd-8eec-a865025f5905)

### Build Version

2024.10.0 (1635)

### What server are you connecting to?

Self-host

### Self-host Server Version

Vaultwarden 1.32.5-d7adce97 (latest)

### Environment Details

- iPhone 12 Pro, iOS 18.1.1 (latest)
- Apple Watch Series 9, watchOS 11.1 (latest)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

It has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by navels** [comment]
Aha, had to go into TestFlight and enable "Show App on Apple Watch".
