### ISSUE TITLE
URI-specific match detection isn't respected during auto-fill

### ISSUE THREAD

**Issue by Insprill** [bitwarden/ios#1203]
### Steps To Reproduce

1. Save two passwords, each with a different subdomain on the same domain, both with `Host` match detection.
2. Try to auto-fill the credentials on both subdomains.
3. Both subdomains will try to autofill the same item. Tapping the key icon to pick which item to fill will correctly only list the item matching the host.

### Expected Result

Autofill should respect the selected match detection for each item.

### Actual Result

Auto-fill always lists the first item according to the default match detection, ignoring the match detection of the individual items.

### Screenshots or Videos

![2024-12-11_19-28](https://github.com/user-attachments/assets/90eb9220-6ee5-411c-a071-5a14ee233f67)

### Additional Context

This is a significant issue for me, as I host several services under different subdomains on my primary domain. All of these passwords are set to host matching, but when logging in from my phone, it always suggests the item from one service, and I have to pick the correct one manually.

### Build Version

2024.11.0 (1680)

### What server are you connecting to?

Self-host

### Self-host Server Version

Vaultwarden 1.32.6

### Environment Details

**Device:** iPhone 8+
**IOS:** 16.7.10

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

You might have to try with exact matching - https://bitwarden.com/help/uri-match-detection/#exact

**Comment by Insprill** [comment]
That's not the behaviour I'm looking for. Host matching works exactly as I want it to everywhere *except* for IOS autofill. The browser extension correctly autofills only the item for the subdomain I'm on, and so does the mobile app if you press the key to see all items (shown in screenshot). It's *only* that autofill button above the keyboard that doesn't respect match rules. I tried setting both items to exact matching anyways and it behaves the same.

**Comment by vvolkgang** [comment]
@Insprill There's a callout for that behaviour in our host match detection [docs](https://bitwarden.com/help/uri-match-detection/#host), our app doesn't get the full url from the OS for QuickType suggestions.

**Comment by zmc** [comment]
> [@Insprill](https://github.com/Insprill) There's a callout for that behaviour in our host match detection [docs](https://bitwarden.com/help/uri-match-detection/#host), our app doesn't get the full url from the OS for QuickType suggestions.

Seems not entirely accurate as I can only reproduce this on iOS in Firefox - not Safari
