### ISSUE TITLE
iPad app won’t launch: “An error has occurred”

### ISSUE THREAD

**Issue by MJJBennett** [bitwarden/ios#1229]
### Steps To Reproduce

1. Log in to app
2. Error is produced after some delay (before any passwords load)

### Expected Result

Able to open the app without errors

### Actual Result

Error is produced on log in: “An error has occurred”

### Additional Context

I updated the app and restarted both the app and iPad. This is the version of the app that says “fixes for [this error]” in the update notes so I figured I would create a ticket as it is indeed not fixed. 

### Build Version

2024.12.0

### What server are you connecting to?

US

### Environment Details

iPad Air 13” (M2), iPadOS 18.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Thank you for contacting Bitwarden. I'd be happy to help with this today.

Can you please try uninstalling the app, then restarting your iPad, then re-installing from the App Store once more.

If the issue continues, please feel free to contact Bitwarden support at https://bitwarden.com/help

**Comment by MJJBennett** [comment]
> Thank you for contacting Bitwarden. I'd be happy to help with this today.
> 
> Can you please try uninstalling the app, then restarting your iPad, then re-installing from the App Store once more.
> 
> If the issue continues, please feel free to contact Bitwarden support at https://bitwarden.com/help

Hi, that does indeed fix the issue, thanks.
