### ISSUE TITLE
autofill not working properly in any other browser than safari

### ISSUE THREAD

**Issue by speedy1804** [bitwarden/ios#1232]
### Steps To Reproduce

1. Download one of the tested browsers (Brave, Google Chrome, Quetta, Arc Search,...) on your device
2. Try to login with your credentials on https://ea.com or https://instagram.com (for example)

### Expected Result

My default iOS keyboard will suggest me my username, password and the TOTP code due to activated bitwarden autofill in any app or browser.

### Actual Result

Only in Safari does it work perfectly that Bitwarden Autofill suggests my credentials. In every other browser I tested, the username and TOTP code for my example website are not suggested, but the password is.

### Screenshots or Videos

(**Safari**, everything works as it should --> username, password and totp autofill are suggested for autofill)
https://github.com/user-attachments/assets/59e6d863-6a42-47af-83af-7ebe6abab990

(**Brave**, does not suggest me username and totp autofill)
https://github.com/user-attachments/assets/b21a0b29-1006-4c25-8872-1d8ba48f3d22

(**Google Chrome**, does not suggest me username and totp autofill)
https://github.com/user-attachments/assets/e441d9f6-d04b-47a5-984f-17e4221b6eb3

(**Quetta Browser**, does not suggest me username and totp autofill)
https://github.com/user-attachments/assets/2cd4e70a-2bf8-4162-84bb-c8e3dcc9aecb

(**Arc Search**, does not suggest me username and totp autofill)
https://github.com/user-attachments/assets/d46f6742-f252-4aaf-bc5f-98f7bcde2c78

### Additional Context

I have tested this possible bug on my iPhone and iPad and also on several different sites. I used https://ea.com for the videos, but the same problem also occurs with https://instagram.com or https://id.galaxus.eu/, for example. These are only selected examples, but I am relatively sure that this problem occurs on even more websites.

However, I would like to point out that this problem does not occur with every website without exception, but with many. 
Feel free to ask me if anything is incomprehensible.

### Build Version

Latest update - Version: 2024.12.0 (1740)

### What server are you connecting to?

US

### Environment Details

- Device: iPhone 14, running latest iOS version (18.2)
- Device: iPad Pro (M2), running latest iPadOS version (18.2)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Can you make sure the vault item you're attempting to autofill contains the correct URI for that site? 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by speedy1804** [comment]
which browser did use to reproduce?

**Comment by Gerardv514** [comment]
Wow, I think the bigger problem (as an example in the safari browser) there were 3 total calls for Face ID. This is so inefficient and slow when autofilling. It should prompt face id for the very first time when clicked to fill username/email and then after that it shouldn't keep prompting for biometric authentication. If fill is happening in quick succession bio metric verify on first fill, then just fill subsequent. 

For security if after some time elapses after first fill and verification, then you can re-require bio metric verification again. 

Just seemed like a slow process.
