### ISSUE TITLE
Apple Watch app crashes on launch

### ISSUE THREAD

**Issue by infinitepower18** [bitwarden/ios#702]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open the Apple Watch app

### Expected Result

The watch app should launch normally.

### Actual Result

The watch app instantly crashes upon launch.

### Build Version

2024.6.1 (1151)

### Environment Details

- iPhone 13 mini, iOS 17.5.1
- Apple Watch SE 1st gen, watchOS 10.5

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @infinitepower18,

Thank you for your report. We were able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by infinitepower18** [comment]
It still crashes on launch with the latest update.

**Comment by TheBig-O** [comment]
I am having this same issue. I have not seen the watch app open successfully.

**Comment by motamedn** [comment]
Same issue here.

**Comment by TheBig-O** [comment]
This issue shows closed but the problem remains. Watch app refuses to open after uninstalling and reinstalling. Does not seem fixed.
