### ISSUE TITLE
Autofill on ipados doesn’t respect match detection when http or https is in uri 

### ISSUE THREAD

**Issue by xternaal** [bitwarden/ios#704]
### Steps To Reproduce

On Ipados, the bitwarden app will show autofill suggestions for all entries that include the base domain IF the password entry has http or https at the start of the uri.

For instance if i have 3 different password entries in my vault for 3 different services:
http://sub1.example.com
https://sub2.example.com
https://sub3.eample.com 

If I go to **http://sub1.example.com**  it will offer to autofill all sites for example.com regardless of what match detection is set to (doesn’t matter if default is selected or override is set specifically for each entry).

Now if i go in and remove the preceding http:// or https:// from the uri for each password. It wont show any entries for the quickfill popup, but will show the correct one if you tap on “passwords”

### Expected Result

When setting match detection to Host (either as the default option or specifically for each entry) the http and https scheme should be ignored and only those entries with the matching full host should be displayed.

### Actual Result

If I go to **http://sub1.example.com**  it will offer to autofill all sites for **example.com** regardless of what match detection is set to (doesn’t matter if default is selected or override is set specifically for each entry).

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.6.0 (7846)

### Environment Details

Ipad Pro 11” 2021

**Comment by Krychaz** [comment]
Hello there,

Have you tried choosing match option 'exact'

**Comment by xternaal** [comment]
Yep, I have tried all different options.

I have actually narrowed it down, I believe it is an Ipados feature which loads the usernames before you do faceunlock. It shows the usernames of all matches and then when you click one it asks for face id.

Then it  autofills the password and proceeds. You don’t need to select anything inside bitwarden.

However, if you click “bitwarden” instead of the prefill options it will load bitwarden, respect the correct uri and only show the correct login details. 

So for instance lets say you have the following hosts all set to match “host” -

https://sub1.example.com
https://sub2.example.com
https://sub3.example.com

Not matter what you set the match uri to, it will always show all hosts  if you visit any *.example.com domain. It is as if the match domain option is set **but only in the pre-fill options shown on the keyboard bar/pop-up**

If you then click the option to look for more passwords in bitwarden, it will ask for faceid and then only show the correct “host” match once bitwarden is fully unlocked. 

I don’t understand the process, obviously ipados has some ability to read the usernames for a site from  bitwarden  prior to actually having faceid unlock it, but that process doesn't respect the uri matching. It appears to only match on domain. This might be a limitation of that feature.

On android for instance this quick load feature doesn’t exist. It recognises a password field, offers to open bitwarden, you unlock and then it matches and you select the login

**Comment by micahblut** [comment]
iOS lets Bitwarden provide a list of available credentials to the operating system. This list is stored in a secure cache so that autofill can suggest credentials even when the Bitwarden app is locked. However, when using this feature, iOS is providing the match detection, not Bitwarden. This means specific URI matching rules you have set on your items will not apply when using the QuickType or iOS bottom sheet autofill suggestions.
