### ISSUE TITLE
Secure Note "Notes" field does not allow multiple lines when creating/editing

### ISSUE THREAD

**Issue by hayden36** [bitwarden/ios#709]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Make a Secure Note
2. Open the "Notes" text field
3. Press the "return" key to try make a new line.

### Expected Result

1. A new line should be created in the text field.

### Actual Result

1. The text field does not allow multiple lines to be added. The keyboard is dismissed and the text field is unfocused.

### Screenshots or Videos

<details><summary>Video of editing a Secure Note</summary>

https://github.com/bitwarden/ios/assets/132246021/b0479151-6cb7-42aa-94db-64d44df96fea

</details> 

<details><summary>Viewing a Secure note with multiple lines</summary>
<p>

Viewing a secure note with multiple lines displays correctly. The issue is with creating or editing notes.

![Screenshot 2024-07-07 at 8 29 00 PM](https://github.com/bitwarden/ios/assets/132246021/9376fda3-400f-43e0-af11-41ddabe3cb46)

</p>
</details> 

### Additional Context

Viewing a note that has multiple lines will still display multiple lines in the text field, however editing or creating a new note does not allow multiple lines.

### Build Version

2024.6.1 (1151)

### Environment Details

- Device: iPhone 15
- OS Version: iOS 17.5.1 (21F90)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
This is fixed in the latest update, thanks for the report!
