### ISSUE TITLE
Bitwarden Beta Set Chinese Language Error

### ISSUE THREAD

**Issue by lgs6** [bitwarden/ios#747]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

Language settings, select Chinese, restart the application or display English

### Expected Result

Set Chinese display English, hope to fix it as soon as possible, thank you

### Actual Result

Set Chinese display English, hope to fix it as soon as possible, thank you

### Screenshots or Videos

![IMG_3082](https://github.com/user-attachments/assets/96b29b57-fd6a-4895-ba10-98a04d192761)

### Build Version

2024.7.1（1218）

### Environment Details

iPhone15pro ios17

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by NovaSilentium** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by gzxiexl** [comment]
+1

© Bitwarden Inc. 2015-2024

Version: 2024.9.1 (1092)

-------- Device --------

Model: iPhone15,3
OS: iOS 18.0

------- CI Info --------

Branch: main
CI Run Attempt: 1
CI Run ID: 10890816915
CI Run Number: 92
Commit hash: 846669a96cfdaa1086e8dcc259d1fa2bf24a08b2
Repository: https://github.com/bitwarden/ios

**Comment by jiaobaba1027** [comment]
me too

**Comment by jiaobaba1027** [comment]
Whether purchasing paid services can solve this problem

**Comment by charley008** [comment]
2024-9-25 +1

© Bitwarden Inc. 2015-2024

Version: 2024.9.2 (1106)

-------- Device --------

Model: iPhone16,2
OS: iOS 17.7

------- CI Info --------

Branch: main
CI Run Attempt: 1
CI Run ID: 10965647830
CI Run Number: 106
Commit hash: 72cc8bd9912ea6b24d9f3b483c0ca0628e190028
Repository: https://github.com/bitwarden/ios

**Comment by w9315273** [comment]
不打算修复了

**Comment by Shoukon** [comment]
Traditional Chinese is also the same

**Comment by charley008** [comment]
两个月了。都没修，

**Comment by easyalx** [comment]
两个月了，没有修复计划吗？

**Comment by xiaobaiya8** [comment]
Three months later, no progress.

**Comment by dzb123112** [comment]
意思是还没修复呗

**Comment by jiaobaba1027** [comment]
两个月了屁动静都没有，连续更新了两个版本，就是不更新适配中文，估计在搞歧视吧





------------------ Original ------------------
From: dzb123112 ***@***.***&gt;
Date: Wed,Oct 30,2024 7:03 PM
To: bitwarden/ios ***@***.***&gt;
Cc: jiaobaba1027 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [bitwarden/ios] Bitwarden Beta Set Chinese Language Error (Issue#747)





 
意思是还没修复呗

**Comment by gzxiexl** [comment]
安卓版本的中文没问题 就ios版不行 醉了 几个月了还没修复😳

**Comment by w9315273** [comment]
11月5号 1651版本 已修复问题

**Comment by sunxiang0918** [comment]
> 11月5号 1651版本 已修复问题

谢谢提醒,   升级后,还需要再重新切换一下语言. 否则还一直是英文..
