### ISSUE TITLE
Face ID not working for auto-fill

### ISSUE THREAD

**Issue by bobbyalderson** [bitwarden/ios#748]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open a non-Bitwarden app requiring login credentials
2. Use iOS autofill on the login form to open the Bitwarden verification screen

### Expected Result

With Face ID enabled in the app, I would expect the Bitwarden auto-fill verification popup to trigger Face ID (as it does in the existing non-beta app).

### Actual Result

Bitwarden auto-fill verification popup asks for PIN (if enabled) or master password, with no Face ID trigger or option.

### Additional Context

Face ID is enabled in Bitwarden and works to unlock the Bitwarden app directly, but not for filling any login credentials.
Bitwarden Beta is the only app enabled in iOS password options.

### Build Version

2024.7.1 (1218)

### Environment Details

iPhone 13
iOS 17.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ismailkarsli** [comment]
Same problem on iPhone 14 PM, iOS 17.5.1.

**Comment by jtodddd** [comment]
Hi there,

This issue has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by SudoEvan** [comment]
Hello,

I'm having the same issue:

Environment Details:

iPhone 15 Pro Max
iOS 17.5.1

Build Version:

2024.7.2 (1233)

I'll dig into the issue a little now to see if I can fix (as a community member).

**Comment by vvolkgang** [comment]
Can you test the most recent build and let me know if this is still happening?

**Comment by ismailkarsli** [comment]
> Can you test the most recent build and let me know if this is still happening?

It was not working at first but now working after I turned off then on the "Unlock with PIN" option. So it's working as expected now 👍

**Comment by SudoEvan** [comment]
This is working now. Disabling and enabling PIN didn't fix it for me however, I had to first login once with Master Password and then subsequent attempts used FaceID.

**Comment by bobbyalderson** [comment]
Same as above, I had to log in with master password before it would work but autofill now triggers Face ID correctly 👍
