### ISSUE TITLE
Spacebar missing from keyboard in URI field, causing matching issues

### ISSUE THREAD

**Issue by willquill** [bitwarden/ios#776]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Be registering an account in an iOS app/website (any app or browser) not previously registered to Bitwarden.
2. Tap "Passwords" above default iOS keyboard, which will open the Bitwarden app overlay if Bitwarden is your default iOS password manager.
3. Tap the `+` in the upper right to create a new vault item.
4. The URI will pre-populate with the URI from which you initiated the Bitwarden overlay.
5. You will be unable to navigate to the end of the URI, as there is no spacebar on the keyboard. Nor will you be able to create an additional URI.

### Expected Result

At least one of these things should occur:

1. I should have the ability to quickly navigate to the end of the URI so that I may backspace.
2. I should be able to create a second URI. This option does not exist after clicking the "plus" in the Bitwarden overlay after tapping "Passwords" on an iOS keyboard after tapping the registration field on a website or app. However, the option for a second URI is present in the app itself.
3. If my default URI match detection is regular expression, then when auto-populating the URI field, do not include anything after the first `/`

### Actual Result

I am stuck generating credentials that I am unable to use, as immediately after creation, the absurdly long default URI does not match on the website I just used to create the credential.

### Additional Context

For users who set their Default URI match detection to "Regular expression," the default URI that populates a new item is often an incredibly long URI that cannot be identified via regex. For example, creating a Microsoft account will use a default URI of:

```
https://login.live.com/oauth20_authorize.srf?client_id=10fa57ef-4895-4ab2-872c-8c3613d4f7fb&scope=openid+profile+offline_access&redirect_uri=https%3a%2f%2fwww.microsoft.com%2fcascadeauth%2faccount%2fsignin-oidc&response_type=code&state=CfDJ8GIDTS11_mxJlLbEvLbfH9PTNbqTjCdz_9Zd0R2NgZdNBsJFzMFE1zH5-ryWZR-f0pnX3gA8O2tdRjh6K0r3VlILLbC7i-BlPqAt2O_c8kzMquAY2dFwrHutUEMGAZMwvvFe8VhiOmi5gWMKv15iX8U4Y-tYt1dmYT1FpGBt46y06iUdVKrRwKA3s3BFgFx5TBmc7H50UTqNyPWjb_dkg74OEOHALeIn9cv2JAxP6qpTZDYHaLVWWLSCbxIZGc4k8M_aKnlOmwuSizwdD3iviTFvpS1mh0C3LofSdyefAHlSVKT0aoTYUfb03RYXM0RhgeCjQExrBNHPcLpYxuUhXd7dtNRipjsrZ-AhkhBLJpbW8aQQdVD3PAH6La3VjnttdS14LCfad25e6yY_1ZJJ-rKC020kdv5XsSGmaSfoTKFuUmHEkaP2lkWDnZ_MZtP-jTg2b1GHmlAR7aulXcAdFmnn1YCQUIG0L2ceKUulvgAv&response_mode=form_post&nonce=638579566935836623.OGNkYmIxOWItMjJlZC00M2ZkLTliNmItY2ZmYzExODg2NTBjMjZkOGFiMDMtY2NjMS00MTQ0LWI2NzAtM2I3ZWIwZmY5NTcw&code_challenge=sLdQIPFRar-FryrK9Cuh_RW7bkyU4rQDUnktIjBEP-Q&code_challenge_method=S256&x-client-SKU=ID_NET6_0&x-client-Ver=7.6.0.0&uaid=238a1c4164224fcfa718cf4616468121&msproxy=1&issuer=mso&tenant=consumers&ui_locales=en-US&client_info=1&epct=PAQABDgEAAAApTwJmzXqdR4BN2miheQMYfxuoZUWmuct8nD9XwRyLHV_6eO1NUebCUs7fI2bP0vpvcDx7X2bOZmtBj8ukX8gquIiweuBHAQ5ZPSAxTvfoor2PQxyse6shIdJEw_-y9O_tPWSdvXny_GMPZghpX73rzGC8VO048vDqN3PDG-XTb-MBRo3EdE5URa5GvpibiE6anIiSVTphWJvQCJjVtDmse_8dUqbfLIrlJW2BDlXjbyAA&jshs=0&claims=%7b%22compact%22%3a%7b%22name%22%3a%7b%22essential%22%3atrue%7d%7d%7d#
```

Developer solutions:

- (preferred) When auto-populating the URI field, do not include anything after the first `/` if your default URI match detection is regular expression.
- (workaround) Provide a spacebar on the keyboard chosen for the URI field
- (workaround) Provide the ability to add a second URI in the the "new item" overlay. 

My personal workaround as an end user:

- Instead of generating the new vault item in the overlay directly from the website at which I am registering an account, I switch to the Bitwarden app and create the item there first. Then I can navigate back to the website and populate it with the pre-created vault item.

### Build Version

2024.6.0 (7846)

### Environment Details

- Device: iPhone 13 Pro
- OS: 17.5.1, but the issue has been occurring for several releases, if not all of them.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
