### ISSUE TITLE
Can’t set Watch app as complication

### ISSUE THREAD

**Issue by cbdreinulldrei** [bitwarden/ios#790]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to Watch app
2. Edit your current watch face.
3. Try setting a complication, try choosing Bitwarden.

### Expected Result

Bitwarden Watch app Set as complication.

### Actual Result

Only works for the .NET app. Native iOS app can’t be set as a watch complication.

### Build Version

1263

### Environment Details

iPhone Pro Max 15 1TB with iOS 17.6.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @cbdreinulldrei,

Thank you for your report. This matter has been escalated for further investigation; If you have more information that you think may assist us, please feel free to add it below. 

Thank you again,

**Comment by cbdreinulldrei** [comment]
Just lmk what to install or test and I’ll happily do this.

For the record: the watch is an AW Ultra 1st gen with latest watchOS 10.6. The old watch app via the .NET application works fine.

**Comment by cbdreinulldrei** [comment]
Just installed Testflight version 2024.8.0 (288) which has the same issue. It does show a working watch app but this app can't be set on the watch face as a complication. The whole section "Bitwarden" with any potential offerings is gone.
