### ISSUE TITLE
[Bug] Accessibility, VoiceOver: The names and item counts of vault section headers are treated as 2 separate accessibility elements, making VoiceOver navigation unnecessarily cumbersome.

### ISSUE THREAD

**Issue by robin24** [bitwarden/ios#810]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. In Settings > Accessibility, turn on VoiceOver.
2. Open Bitwarden > navigate to the Vaults tab.
3. Using VoiceOver swipe gestures, navigate through the various section headings and observe speech output and focus behavior.

### Expected Result

VoiceOver treats the section name and item count as one element, resulting in speech output such as "Favorites, 4"

### Actual Result

The section name and item count as 2 separate accessibility elements that are individually focusable. This makes it unnecessarily cumbersome to navigate the UI using VO swipe gestures, and the relationship between the section name (e.g. "Favorites") and the item count (e.g. 4) may not be clear to some users.

### Build Version

Bitwarden Beta, Version 2024.7.3 (1263)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team along with your pull request.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
