### ISSUE TITLE
Automatic syncing by push notifications is not working

### ISSUE THREAD

**Issue by jluo98** [bitwarden/ios#874]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Keep the app open in the foreground. 
3. Make a change in web vault, e.g. change the name of a folder. 
4. Server pushes the change to clients. 

### Expected Result

The change is reflected in the app within a few seconds. 

### Actual Result

The change is not synced unless manually refreshed. 

### Screenshots or Videos

https://github.com/user-attachments/assets/bbd6804a-1590-41cc-a78d-52ef3e8dff06

### Additional Context

Auto sync is working on the current legacy app (2024.7.1)

### Build Version

2024.8.0 (284)

### Environment Details

Tested on
- Device: iPhone 15 Pro Max
- OS Version: iOS 18.1 Dev Beta 2 (22B5023e)

and
- Device: iPad Pro M4 (2024) 13-inch
- OS Version: iOS 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Hi There,

It is important to note that Vaultwarden (the new name for Bitwarden RS) is not associated with Bitwarden.

Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. The security audits granted to Bitwarden do not apply to Vaultwarden, and the Bitwarden support team is not able to respond to questions regarding Vaultwarden.

Bitwarden also offers a self-hosted option, which many of our customers run in an air-gapped environment.  You can find information on this here:

https://bitwarden.com/help/install-on-premise-linux/ 

https://bitwarden.com/help/install-and-deploy-offline/ 

I hope you find this helpful. 
This issue will now be closed, Thank you!

**Comment by jluo98** [comment]
> It is important to note that Vaultwarden (the new name for Bitwarden RS) is not associated with Bitwarden.

My mistake. Should've done the video on the official vault. Same behavior on Bitwarden.com. See attached video. 

https://github.com/user-attachments/assets/d8a6e05b-0d1b-46b0-b34d-38cbf62533a8

**Comment by jluo98** [comment]
My mistake. It's the same behavior on bitwarden.com. I've opened a new issue instead of editing this one to avoid any confusion #875.
