### ISSUE TITLE
Automatic syncing by push notifications is not working with Bitwarden.com

### ISSUE THREAD

**Issue by jluo98** [bitwarden/ios#875]
### Bitwarden Beta

- [x] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Keep the app open in the foreground. 
2. Make a change in web vault, e.g. change the name of a folder. 
3. Server pushes the change to clients. 

### Expected Result

The change is reflected in the app within a few seconds. 

### Actual Result

The change is not synced unless manually refreshed. 

### Screenshots or Videos

https://github.com/user-attachments/assets/d8a6e05b-0d1b-46b0-b34d-38cbf62533a8

### Additional Context

Auto sync is working on the current legacy app (2024.7.1). Same behavior on bitwarden.com and self-hosted Vaultwarden. 

### Build Version

2024.8.0 (284)

### Environment Details

Tested on
- Device: iPhone 15 Pro Max
- OS Version: iOS 18.1 Dev Beta 2 (22B5023e)

and
- Device: iPad Pro M4 (2024) 13-inch
- OS Version: iOS 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by steve28** [comment]
I am seeing this as well on iOS with version 2024.8.1. Push updates not working.

**Comment by snowie2000** [comment]
I'm on the latest 2024.9.2, push notification for login devices can only be received when the app is open. Sync push are nowhere to see and doesn't work at all...

**Comment by ROPiator** [comment]
Hello, I have the same issue on my iPhone with the latest version of Bitwarden (2024.11.0 - 1680). Background notifications for "Login with device" function are not delivered, but work normally when the app is launched. Automatic sync is also not working, neither in foreground and background.

**Comment by KatherineInCode** [comment]
Hi! 👋🏻 I've been looking into this issue, and it's a tricky one. I haven't yet been able to reproduce it, myself, though I've been trying.

For people who are encountering it, some information that might help me track down what's going on:

1. To double-check, are push notifications turned on in iOS settings for the Bitwarden app? And which kind of notifications do you have set—banners/sounds/badges and if banners what style? (Settings -> Apps -> Bitwarden -> Notifications)
2. Is Background App Refresh turned on or off for the app? (Settings -> Apps -> Bitwarden)
3. In the app, what Session Timeout and Session Timeout Action do you have set? (Settings -> Account Security)
4. Were you a user of the MAUI app, before the native-app rewrite?

Thanks!

**Comment by ROPiator** [comment]
Hi Katherine,

1. Notifications for Bitwarden app are turned on (Lock screen, Notification Centre Banners), Banner style set to "Temporary", Sounds and Badges on,
2. Background App Refresh is turned on,
3. Session Timeout is set to 15 minutes and action set to "Lock"
4. No, I haven´t used any other apps before

![IMG_1044](https://github.com/user-attachments/assets/17223f77-a717-4753-b0f6-fc1fbefe39f7)
![IMG_1045](https://github.com/user-attachments/assets/3daec4b9-19ce-409f-b21a-7eb0a9bc62cd)
![IMG_1046](https://github.com/user-attachments/assets/9bd9f0a4-4c63-4798-8400-039cdafa6903)
