### ISSUE TITLE
Unable to login "An error has occurred" selfhosted

### ISSUE THREAD

**Issue by NLfrans** [bitwarden/ios#897]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. start bitwarden
2. enter you e-mail and select selfhosted
3. click on "Continue"
4. Enter you password
5. Click op "Login using password"
6. Error message "Er is een fout opgetreden"

The second option "Loggin with device". is also giving Error

On my iMac i have no issues with logging in  

### Expected Result

I can not use my passwords

### Actual Result

error message "er is een fout opgetreden"

### Screenshots or Videos

![IMG_5260](https://github.com/user-attachments/assets/db3beb71-241b-4043-b528-41729101108c)

### Build Version

2024.8.1

### Environment Details

iPhone 15 17.6.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by basketshoe** [comment]
Same generic for me, works fine on Safari from the same device

**Comment by sammbw** [comment]
Hi there,

Can you please ensure that your Bitwarden server environment is up to date?

Is it possible you are using a Vaultwarden server, rather than a Bitwarden server?

**Comment by NLfrans** [comment]
Thank you for helping out.

After upgrading Vaultwarden from 2013.10.0 to 2024.6.2 i have no issues more.

**Comment by sammbw** [comment]
Thanks for confirming this worked in your case today.

It is important to note that Vaultwarden is not associated with Bitwarden.  Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organisation.  The security audits granted to Bitwarden do not apply to Vaultwarden, and the Bitwarden support team is not able to respond to questions regarding Vaultwarden.

With that said, there are no licensing restrictions to stop you from using the Bitwarden clients with any 3rd party servers - we cannot guarantee compatibility between latest client updates and Vaultwarden server however.

This issue will now be closed.
