### ISSUE TITLE
Vault selector doesn’t reflect active selection

### ISSUE THREAD

**Issue by stijneikelboom** [bitwarden/ios#898]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to the `Vaults` tab
2. Tap on `...` next to `Vaults: All`
3. Tap on any other option than `All vaults`

### Expected Result

The bar shows `Vaults: {Vault name}` and the check mark in the dropdown is next to the selected vault/organization.

### Actual Result

The actual filtering works, but the bar keeps showing `Vaults: All` and the check mark is always next to `All vaults`.

### Build Version

2024.8.1

### Environment Details

- Device: iPhone 14 Pro
- OS Version: iOS 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Hinton** [comment]
Hi @stijneikelboom,

This should be fixed in https://github.com/bitwarden/ios/pull/881 and is included in the latest release 2024.9.1.

**Comment by stijneikelboom** [comment]
Can confirm that this has been fixed in 2024.9.1. Thanks!
