### ISSUE TITLE
BitWarden App can't login

### ISSUE THREAD

**Issue by VolleyTom8** [bitwarden/ios#906]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1) Start App
2) Change to SelfHosted Server
3) Try to Login with EMail and Password
4) ERROR: "An Error Occured"

SelfHosted Server is OK, because PlugIn of WebBrowser in Windows is Working and also the WebLogin.

### Expected Result

Login to BitWarden

### Actual Result

Can't Login

### Screenshots or Videos

![b7b3af64-9c88-4071-bf16-d106c612b775](https://github.com/user-attachments/assets/7fb57eb1-f998-4d6e-9bf8-18a0b87c360e)

### Build Version

2024.8.1

### Environment Details

IPhone14, OS 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by catatonicChimp** [comment]
Was also running into the same issue, iphone12pro, IOS 17.6.1
old app was working fine as well as the desktop and firefox plugins

tried logout/login/restart/uninstall/reinstall with the same issue reappearing

Solved by updating the Vaultwarden docker image to Version: 1.32.0 
and it started working again.

**Comment by Adedamola-Aina** [comment]
Similar issues https://github.com/bitwarden/ios/issues/897
