### ISSUE TITLE
App stalls when network connection to server is unavailable

### ISSUE THREAD

**Issue by holow29** [bitwarden/ios#907]
### Bitwarden Beta

- [x] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

Self-host bitwarden only accessible in a local network
Connect phone to local network, login to app, sync vault
Disconnect from local network (thereby making Bitwarden server inaccessible)
Attempt to open app (or autofill a password)

### Expected Result

App opens as normal with cached vault (but can't sync)
Able to autfill items from cached vault

### Actual Result

If app is already open in background, it will have a loading wheel in the vault tab; you can go to a different tab and back to vault to get it to load properly. If app is not already open (force closed), it hangs on splash screen until it is backgrounded then brought back.
Autofill prompts through native iOS keyboard but does not open app overlay

### Additional Context

There seem to be issues with the app when a network connection cannot be made to the server. Things like opening the app, viewing the vault, autofilling should all still work without a connection to the server, but that is not currently the case.
I think this is similar to being on a restricted network that does not have access to Bitwarden server for non-self-host. e.g. airplane WiFi

### Build Version

1052

### Environment Details

iPhone 14 Pro
iOS 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by allddd** [comment]
Having the same issue with 2024.8.1 (1052) on iOS 17.6.1 (iPhone 14 Pro).

**Comment by holow29** [comment]
Fixed in 1092
