### ISSUE TITLE
Empty Vault after update

### ISSUE THREAD

**Issue by Zoriot** [bitwarden/ios#911]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Update via App Store (Old C# based App)
2. Login via E-Mail, Master Password and 2FA Code

### Expected Result

You see all the passwords and can use them

### Actual Result

Empty vault, without any of the Passwords. 

### Additional Context

Deleting the App and installing it new fixes the issue. Maybe its related that i tried to login via the Browser Extension first. 

### Build Version

2024.8.1 (1052)

### Environment Details

- Device iPhone 14 - iOS-Version 18 (22A5350a) - latest beta

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @Zoriot,

Thank you for reporting this. The client may have needed a bit more time to download the vault and decrypt the vault items; I am unable to reproduce this in testing after updating to Bitwarden 2024.8.1 on iOS 17.6.1.

If you encounter this again, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
