### ISSUE TITLE
Account selector not displaying and requires master password

### ISSUE THREAD

**Issue by AlexFeldmeier** [bitwarden/ios#929]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Add 2 or more accounts
2. Tap profile picture in top left of “vaults” screen
3. At least 2 accounts will be hidden behind the app bar

### Expected Result

- Account selector should be displayed under the app bar
- Selecting another account should let you sign in with Face ID 

### Actual Result

- At least 2 accounts are hidden behind the app bar
- Selecting another account forces you to type the master password each time even if you enabled Face ID for both accounts

### Build Version

2024.8.1 (1052)

### Environment Details

- Device: iPhone 15 Pro Max 
- OS: iOS 18 RC

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @AlexFeldmeier,

Thank you for reporting this. I tested this on iOS 17.6.1 with Bitwarden 2024.8.1, and I was able to view the 2 logged-in accounts, and switch between them successfully and to unlock both using Touch ID on an iPhone SE 2020; I suspect that this is related to the RC release of iOS 18. Generally speaking, it's recommend to stick to Stable Channel releases for an optimal experience. If you continue to experience this on the stable release of iOS 18, please feel free to [get in touch](https://bitwarden.com/help/) with us and we'll have a look at this together.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by TheRittler** [comment]
I can confirm this happening on the stable version of iOS 18. Is it possible to reopen it?
