### ISSUE TITLE
Forced login via SSO on boot, unable to login any other way.

### ISSUE THREAD

**Issue by Herctic** [bitwarden/ios#949]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open the app or try autofilling a password in Safari
2. This popup shows: ![IMG_2248](https://github.com/user-attachments/assets/5a8660af-be7d-467e-bbec-283f56800261)
3. Press the X and the screen stays blank

### Expected Result

The app should open normally and either prompt me to re-login, or re-enter my pin to gain access to the vault.

### Actual Result

The app currently opens the SSO login popup when being accessed from a force closed state and when trying to autofill a login from Safari.

### Screenshots or Videos

![SSO prompt from cold boot](https://github.com/user-attachments/assets/71e56a1d-d623-4bd5-a3b0-5d4ca3396a22)
![Blank page after X'ing out of the SSO prompt](https://github.com/user-attachments/assets/0a20aa6a-109a-484c-897d-33487bc57f66)

### Build Version

Version 2024.9.1

### Environment Details

- Device: iPhone 13 Pro
- OS version: iOS 18.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ccodykid** [comment]
Can confirm this bug.
I still can autofill credentials with Face-ID though.

**Comment by cbbit** [comment]
Hi there,

I am unable to reproduce this issue, however, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Ethral-T** [comment]
Just updated the app via the AppStore to the most recent version posted.

I'm running into the same issue. I can autofill via the keyboard extension but otherwise I'm forced to enter an SSO Login.



Bitwarden Version: 2024.9.1
iOS version: 18.0
iPhone version: 15 Pro Max

![image](https://github.com/user-attachments/assets/6d0fa68b-0486-4a87-af55-600bdf6c43e2)
![image](https://github.com/user-attachments/assets/574e408e-3d8c-48da-9f23-81af5060128b)

**Comment by flcdrg** [comment]
Seeing this on one family phone already. We're on the "2019 Families Organization" subscription if that's relevant

**Comment by joshuabeny1999** [comment]
Had that issue yesterday too on my sis phone. She had the latest app. 

I am using a self hosted instance and have also a family organisation where I didn't enable SSO. 

Reinstall the app seems to fixed it, hopefully it stays that way.

**Comment by bartvdo** [comment]
had the same problem on a new iphone that had all data transfered from an older phone. I have to wait until restall because deleting it put it on the back of the app download list...

**Comment by gabox7** [comment]
Same issue with iphone 14 pro max ios 17.7 and last version bitwarden. I can fix it reinstalling bitwarden.

**Comment by lfilho** [comment]
+1. And +1 to reinstalling it.

**Comment by Cris70** [comment]
Same problem here on my iPad. Going to reinstall.

**Comment by rayzorfist** [comment]
+1 to this same issue with a new iPhone 14 with data copied from the old iPhone.
Deleting the app and reinstalling allows login to proceed as expected.

**Comment by hawksj** [comment]
Same issue here, iPhone 13 iOS 18.0. App auto-updated on 25th September and autofill pop ups and app both asked for Organization Identifier which I could not provide. Had me worried as I'm abroad with no access to any other devices with Bitwarden. 

Fortunately reinstalling the app resolved the issue here too. All good now.

**Comment by vvolkgang** [comment]
@hawksj can share the app version you're using please? It's in Settings > About

**Comment by hawksj** [comment]
> ~~@hawksj can share the app version you're using please? It's in Settings > About~~
> 
> Edit: for others that have not reinstalled and are still facing this issue, knowing the app version will help us troubleshoot. This is available through iOS Settings > Bitwarden.

Hi @vvolkgang, I've pasted the about section from the app to provide all info about my app at the end of this message. Of course I cannot guarantee this is was the version that was automatically installed via the App Store on 25th September. 

Hope that helps. 

© Bitwarden Inc. 2015-2024

Version: 2024.9.2 (1106)

-------- Device --------

Model: iPhone14,5
OS: iOS 18.0

------- CI Info --------

Branch: main
CI Run Attempt: 1
CI Run ID: 10965647830
CI Run Number: 106
Commit hash: 72cc8bd9912ea6b24d9f3b483c0ca0628e190028
Repository: https://github.com/bitwarden/ios
