### ISSUE TITLE
Vaults tab hangs/spins on startup when server is unreachable

### ISSUE THREAD

**Issue by holow29** [bitwarden/ios#974]
### Steps To Reproduce

1. Open app, login, close app
2. Create a situation where the Bitwarden server/self-host server is unreachable (e.g. airplane WiFi, self-host only available over local network, bitwarden server restricted, etc.)
3. Wait?
4. Open app and unlock

### Expected Result

Vaults tab opens as normal with items displaying

### Actual Result

Vaults tab opens but there is a spinning wheel (as if it is loading) instead of any items displaying. This can be worked around by clicking into another tab and then into vaults.

### Additional Context

Whereas https://github.com/bitwarden/ios/pull/878 fixed the main issue with actually using the app when network connection is unavailable, there seems to be some unintended behavior here still.

This issue requires some time to have passed between the app having been open with a valid network connection and the next time it is open without - I'm not sure about the specifics, but restarting the phone and clearing the RAM don't seem to matter.

The app is clearly trying to reach out to the server this whole time as if the connection to server is restored with app in this state (spinning wheel) and in foreground, vault items then load immediately.

### Build Version

1106

### Environment Details

- Device: iPhone 14 Pro
- OS: iOS 18

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by vfxdev** [comment]
I think my issue is related to this. After being offline from my self-hosted server for around 3.5 days (and everything working perfectly during this time), I suddenly get the "An error has occurred" message and the vault is inaccessible. On four other iOS devices the same thing happened, with the same timing. MacOS client keeps working perfectly.

**Build Version**
1106

**Environment Details**
Device: iPhone 13 Mini
OS: iOS 17.6.1

**Comment by fedemkr** [comment]
Hi there, thanks for the reports. This has been handled by #1078 and will be available in the next release.
